// Mock案例数据 - 当Supabase不可用时使用
import { KnowledgeBaseCase, CaseSource } from './supabase';
import { StatKey } from '@/types';

export const MOCK_KNOWLEDGE_BASE_CASES: KnowledgeBaseCase[] = [
  {
    id: 'mock_case_1',
    title: '安吉"两山理论"实践案例',
    tags: ['生态保护', '绿色发展', '乡村振兴', '可持续发展'],
    category: 'environment',
    author_display: '政府',
    context_summary: '浙江省安吉县通过"绿水青山就是金山银山"理念，将生态保护与经济发展有机结合，实现了从"卖石头"到"卖风景"的转变。',
    conflict_detail: '初期面临经济发展与生态保护的矛盾：传统采矿业带来收入但破坏环境，转型旅游业需要大量投入且见效慢。',
    resolution_outcome: '通过政策引导、产业转型、生态修复，成功打造了"中国美丽乡村"品牌，旅游业成为支柱产业，村民收入大幅提升，生态环境显著改善。',
    expert_comment: '这是"两山理论"的典型实践，证明了生态保护与经济发展可以相互促进。关键在于找到适合本地的发展路径，并坚持长期投入。',
    source: 'official_report',
    status: 'published',
  },
  {
    id: 'mock_case_2',
    title: '十八洞村精准扶贫经验',
    tags: ['精准扶贫', '产业发展', '民生保障', '党建引领'],
    category: 'people',
    author_display: '政府',
    context_summary: '湖南省花垣县十八洞村通过精准识别、精准帮扶、精准管理，实现了从深度贫困村到小康村的华丽转身。',
    conflict_detail: '贫困人口多、基础设施差、产业基础薄弱，村民对扶贫政策理解不一，存在"等靠要"思想。',
    resolution_outcome: '通过"六个精准"（扶持对象、项目安排、资金使用、措施到户、因村派人、脱贫成效），发展特色产业，改善基础设施，激发内生动力，2016年实现整村脱贫。',
    expert_comment: '十八洞村的成功经验在于精准施策、因地制宜，既注重"输血"更注重"造血"，激发了村民的主动性和创造性。',
    source: 'official_report',
    status: 'published',
  },
  {
    id: 'mock_case_3',
    title: '某村集体经济发展困境',
    tags: ['集体经济', '资金管理', '村民矛盾', '治理能力'],
    category: 'economy',
    author_display: '基层干部',
    context_summary: '某村集体账上资金管理混乱，村民对分红方案不满，导致集体资产流失，村民信任度下降。',
    conflict_detail: '村集体账目不透明，部分村干部涉嫌挪用资金，村民要求公开账目和分红，但村干部以"内部事务"为由拒绝。',
    resolution_outcome: '通过建立"三资"管理平台，实行财务公开，引入第三方审计，规范分红制度，逐步恢复村民信任，集体经济重新走上正轨。',
    expert_comment: '集体经济发展必须建立在透明、规范、民主的基础上。财务公开和民主监督是防止腐败、维护集体利益的关键。',
    source: 'field_experience',
    status: 'published',
  },
  {
    id: 'mock_case_4',
    title: '乡风文明建设实践',
    tags: ['乡风民俗', '移风易俗', '文化传承', '村民自治'],
    category: 'civility',
    author_display: '基层干部',
    context_summary: '某村通过制定村规民约、开展文明评选、传承优秀文化，有效改善了赌博成风、不孝不敬等不良风气。',
    conflict_detail: '传统陋习根深蒂固，部分村民对移风易俗有抵触情绪，认为"管得太宽"，新旧观念冲突明显。',
    resolution_outcome: '通过村民代表大会制定村规民约，开展"好媳妇"、"好婆婆"等评选活动，建立红白理事会，引导村民自觉遵守，乡风文明显著提升。',
    expert_comment: '乡风文明建设需要循序渐进，既要尊重传统又要移风易俗，关键在于激发村民的自觉性和主动性。',
    source: 'field_experience',
    status: 'published',
  },
  {
    id: 'mock_case_5',
    title: '环境污染治理案例',
    tags: ['环境保护', '污染治理', '企业监管', '村民维权'],
    category: 'environment',
    author_display: '村民',
    context_summary: '某村附近工厂排放废水废气，导致农田污染、村民健康受损，引发群体性事件。',
    conflict_detail: '企业以"促进就业"为由拒绝整改，村民多次投诉无果，矛盾激化，部分村民采取过激行为。',
    resolution_outcome: '通过环保部门介入、媒体曝光、法律途径，企业被责令整改并赔偿损失，建立长期监测机制，村民权益得到保障。',
    expert_comment: '环境保护不能以牺牲群众利益为代价。必须建立有效的监管机制和维权渠道，平衡经济发展与环境保护。',
    source: 'expert_contribution',
    status: 'published',
  },
  {
    id: 'mock_case_6',
    title: '村民矛盾调解技巧',
    tags: ['矛盾调解', '沟通技巧', '法律运用', '情感疏导'],
    category: 'people',
    author_display: '基层干部',
    context_summary: '两户村民因宅基地纠纷长期不和，多次调解未果，影响邻里关系和村庄和谐。',
    conflict_detail: '双方各执一词，情绪激动，互不相让，调解人员多次介入但效果不佳，矛盾有升级趋势。',
    resolution_outcome: '通过"背靠背"沟通、法律咨询、情感疏导、第三方见证，最终达成和解协议，双方握手言和。',
    expert_comment: '矛盾调解需要耐心、技巧和智慧。要善于倾听、换位思考，既要讲法理也要讲情理，找到双方都能接受的平衡点。',
    source: 'field_experience',
    status: 'published',
  },
];

